# Generated by Django 4.2.23 on 2025-07-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='voter',
            name='user_fname',
            field=models.CharField(max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='user_lname',
            field=models.CharField(max_length=200, verbose_name='Last name'),
        ),
    ]
