# Generated by Django 4.2.23 on 2025-07-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_alter_voter_email_alter_voter_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='email',
            new_name='user_email',
        ),
    ]
