# Generated by Django 4.2.23 on 2025-07-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_rename_email_voter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_app.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.voter')),
            ],
        ),
    ]
