# Generated by Django 4.2.23 on 2025-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
